NumberOfPoints: 1261         
DataFile: zahi_test.dat
Dimentions: 0           
MinTemp:         0.10      
MaxTemp:         1.0      
TempStep:        0.01     
OutFile:          zahi_testi.out
SWCycles:        2000      
KNearestNeighbours:    11  
MSTree|                    
DirectedGrowth|            
SaveSuscept|               
WriteLables|               
WriteCorFile~              
DataIsMatrix: 1
